on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: zuplo/rmoa-action@v1
      with:
        filepath: './openapi.json'
        apikey: ${{ secrets.RMOA_API_KEY }}
    - name: Rate My Open API
      run: rmoa lint 
