on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get checkout
      - uses: actions/checkout@v4

      - name: Rate My Open API
      - uses: zuplo/rmoa-action@v1
        with:
          filepath: './openapi.json'
          apikey: ${{ secrets.RMOA_API_KEY }}